version: '{build}'
build_script:
- cmd: >-
    mkdir build\

    cd build\

    cmake -G"Visual Studio 14 2015 Win64" -DSTANDARDESE_BUILD_TEST=ON -DLIBCLANG_LIBRARY="C:\Program Files\LLVM\lib\libclang.lib" -DLIBCLANG_SYSTEM_INCLUDE_DIR="C:\Program Files\LLVM\lib\clang\3.8.0\include" -DBOOST_ROOT="C:\Libraries\boost_1_60_0" -DBOOST_LIBRARYDIR="C:\Libraries\boost_1_60_0\lib64-msvc-14.0" -DBoost_USE_STATIC_LIBS=ON ..\

    cmake --build .

    tool\Debug\standardese.exe --version

    test\Debug\standardese_test.exe
